[toolchain]
    channel="nightly-2025-09-22"
    components=[
        "rust-src", # Makes the source code of the standard library available for compilation
    ]
    targets=["wasm32-unknown-unknown"]
