[package]
    authors=["TheRealMorgenfrue"]
    description="Database code for WebVOWL Reimagined"
    edition="2024"
    keywords=["rdf", "graph", "sparql", "datafusion"]
    license-file="LICENSE"
    name="webvowl-database"
    readme="README.md"
    repository="https://github.com/WebVOWL/WebVOWL-Reimagined"
    version="0.0.1"

[lib]
    crate-type=["cdylib", "rlib"]


[dependencies]
    grapher={git="https://github.com/WebVOWL/RustGrapher"}
    rdf-fusion="0.1.0"
    horned-owl={git="https://github.com/phillord/horned-owl", rev="c4f7835ecae70b5e7281dc23b9b7fc6daa497f1d"}
    webvowl-parser={path="../parser"}
    tokio = "1.48.0"
    futures = "0.3.31"
